name: Unittest(MSVC)

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  gtest-msvc:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            msvc: "Visual Studio 16 2019"
          - os: windows-2016
            msvc: "Visual Studio 15 2017"

    steps:
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: run unittest
        run: |
          cd test/unittest &&
          mkdir build &&
          cd build &&
          cmake .. -G "${{ matrix.msvc }}" -A x64 -Dgtest_force_shared_crt=TRUE &&
          msbuild ACLibrary.sln &&
          ctest -C Debug -V
